### ISSUE TITLE
Double, Triple, Quadruple Chat Messages in game.

### ISSUE THREAD

**Issue by jbdman** [the-obsidian/DiscordBridge#40] opened 2016-06-19 01:54 UTC
I think this may be an issue with the plugin not closing connections on reload.

**Comment by PassTheMayo** [comment] 2017-01-22 05:58
Reloading a Discord <-> Minecraft plugin should never be a thing. Reload actually shouldn't even be a command in the first place. If you want to apply changes to the configuration file, make sure to stop the server, edit the file, then start the server. Never attempt to reload on any server, this will break a lot more many things than you might think.

**Comment by jacobwgillespie** [comment] 2017-01-22 06:05
To be clear, '/discord reload' should be functional to reload the connection to Discord, but the Spigot '/reload' is definitely unsupported.

**Comment by LividJava** [comment] 2017-02-01 06:20
@jacobwgillespie could you put in the readme in giant text to RESTART the server not RELOAD.... thnx

**Comment by DiamondIceNS** [comment] 2017-04-29 17:44
When developing against the latest JDA version, I had noticed that the `/discord reload` command was spotty and didn't properly kill the running JDA thread, so there would be two asynchronous threads listening for messages and both of them would fire, causing multiple messages to appear. Unloading the plugin with the unsupported `/reload` Spigot command calls the same code so it had the same problem.

This _should_ be fixed with #47. You can use either `/discord reload` or Spigot's `/reload` and it will produce intended behavior in the scope of this plugin. Just be aware that Spigot's `/reload` is a command you should almost _never_ use since most plugins don't support it.

**Closed as completed by DiamondIceNS** 2017-04-29 17:44 UTC
