### ISSUE TITLE
Plugin isnt sending messages to Discord

### ISSUE THREAD

**Issue by mouro001** [the-obsidian/DiscordBridge#19] opened 2016-02-08 12:48 UTC
Isnt sending messages neither recieving from discord.

**Comment by jacobwgillespie** [comment] 2016-02-08 13:19
This is a duplicate of #18 - I should have a fix out shortly

**Closed as completed by jacobwgillespie** 2016-02-08 13:19 UTC

**Comment by mouro001** [comment] 2016-02-08 15:05
just a question, how shortly? if it is 1 day, max 2 i will wait, if not i will move to slack

**Comment by jacobwgillespie** [comment] 2016-02-08 18:52
v1.4.0 is out now and should fix the issue: https://github.com/the-obsidian/DiscordBridge/releases/tag/v1.4.0
