### ISSUE TITLE
after /discord reload plugin doesnt send message to discord 

### ISSUE THREAD

**Issue by mouro001** [the-obsidian/DiscordBridge#22] opened 2016-02-09 12:17 UTC
Everything is working fine til you do /discord reload
If you talk something on chat, you recieve it on chat, but it doesnt send.

**Comment by SinisterRectus** [comment] 2016-02-16 19:29
Errors possible related. Only happens after trying to send a message in-game after reloading.

`[14:27:00] [Netty Epoll Server IO #2/WARN]: org.json.JSONException: JSONObject["id"] not found.
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at org.json.JSONObject.get(JSONObject.java:477)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at org.json.JSONObject.getString(JSONObject.java:723)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at net.dv8tion.jda.handle.EntityBuilder.createMessage(EntityBuilder.java:282)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at net.dv8tion.jda.entities.impl.TextChannelImpl.sendMessage(TextChannelImpl.java:163)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at net.dv8tion.jda.entities.impl.TextChannelImpl.sendMessage(TextChannelImpl.java:137)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at gg.obsidian.discordbridge.DiscordConnection.send(DiscordConnection.kt:29)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at gg.obsidian.discordbridge.Plugin.sendToDiscord(Plugin.kt:30)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at gg.obsidian.discordbridge.EventListener.onChat(EventListener.kt:29)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at java.lang.reflect.Method.invoke(Method.java:498)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:483)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1031)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:980)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:37)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:9)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:115)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at net.minecraft.server.v1_8_R3.NetworkManager.channelRead0(NetworkManager.java:312)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at net.minecraft.server.v1_8_R3.NetworkManager.channelRead0(NetworkManager.java:1)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[14:27:00] [Netty Epoll Server IO #2/WARN]:     at java.lang.Thread.run(Thread.java:745)`

**Comment by jacobwgillespie** [comment] 2016-02-21 15:33
Can you test this again with 1.4.4?  I think I may have fixed the underlying issue.

**Comment by jacobwgillespie** [comment] 2016-02-29 15:06
Closing due to inactivity - if you're still experiencing this on the latest version, feel free to post back.

**Comment by qixils** [comment] 2016-05-04 23:50
I can confirm that this is still happening. Discord -> Minecraft works, but Minecraft -> Discord doesn't. Server needs a restart to work again.

**Comment by jacobwgillespie** [comment] 2017-04-29 20:25
This should be fixed by #47

**Closed as completed by jacobwgillespie** 2017-04-29 20:25 UTC
